### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by petri** [andreikop/python-ws-discovery#5]
Looks like the package could benefit from refactoring the code into several smaller modules?

**Comment by petri** [comment]
For example the following modules:

- wsdiscovery.base (supporting classes such as QName, Scope, Message, Service...)
- wsdiscovery.namespace (namespace definitions - could also fold into .base) 
- wsdiscovery.parsing (functions for parsing WS-Discovery SOAP messages)
- wsdiscovery.generating (functions for generating WS-Discovery SOAP messages)
- wsdiscovery.threading (custom threading classes)
- wsdiscovery.daemon (runnable networking servers that perform the discovery)
- wsdiscovery.util (other functions used by other code)

**Comment by hlamer** [comment]
Looks good

**Comment by petri** [comment]
I took a stab at refactoring; see current master of https://github.com/koodaamo/python-ws-discovery. I also dropped Python2 compatibility `__future__` imports.

**Comment by petri** [comment]
Pushed a `refactoring` branch to this repo too. If we choose to merge that, we can then bump the major version, and suggest that people needing Python2 support should stick to the old version.

**Comment by andreikop** [comment]
Hi

Now the repository looks much more mature. Thank you!

Minor issues:
* Are there any strong reasons to drop Py2 compatibility? I write my new projects on Py3, but a lot of projects still are stuck on Py2 and are not going to migrate. Why don't we allow them to use new clean code layout?
* Remove old file from the repo. Remove executable flag from .py files.
* Update example in README
* Some projects have functionality implemented in submodules but expose public API from root package. I like this approach because in this case users code is not going to break if we change module structure once more. 
`__init__.py`:
```
from wsdiscovery.daemon import WSDicovery
from wsdiscovery.... import (QName, Scope, ...)
__all__ = (WSDicovery, QName, Scope, ...)
```

**Comment by petri** [comment]
Well, old projects can keep using current 0.2 version. And Python2 is going the way of the dodo anyway soonish, so I did not think there'd be much harm. Having said that, the changes were few so I restored the Py2 compatibility in the branch.

**Comment by petri** [comment]
You might want to test the Python2 compatibility - I am on MacOS whose Python2.7 has no `select.poll` so cannot test.

**Comment by andreikop** [comment]
Merged!
Move other public classes to root if you know what is public
